<div id="auth_block">
<form action="/auth/" method="post">
<p><label>E-mail:</label><input class="form-control" type="email" name="email"></p>
<p><label>Password:</label><input class="form-control" type="password" name="password"></p>
<p><input class="btn btn-block btn-primary" type="submit" value="Log in" name="submit"></p>
<a class="btn btn-block btn-primary" href="<?=$router->path('reg')?>">Registration</a>
</form>
</div>