<?php if(!$authorizeSession->isAuthorized()): ?>
	<div class="center-block p-3">
		<?=$sessionAlerts->display()?>
		<form class="auth-form" method="post" action="<?=$router->url('', 'auth')?>">
			<div class="form-group">
				<label><?=_("Name or E-mail")?>:</label>
				<input class="form-control" type="text" name="login" />
			</div>
			<div class="form-group">
				<label><?=_("Password")?>:</label>
				<input class="form-control" type="password" name="password" />
			</div>
			<div class="form-check">
			    <label class="form-check-label">
			      <input name="save-cookie" type="checkbox" class="form-check-input">
			      <?=_("Stay in system")?>
			    </label>
			  </div>
			<button type="submit" class="btn btn-primary btn-block"><?=_("Log in")?></button>
			<a href="#" class="grey-link"><?=_("Forgot password")?>?</a>
			<a href="<?=$router->url("", "reg")?>" class="float-right"><?=_("Register")?></a>
		</form>
	</div>
<?php endif; ?>