<div class='container-fluid p-0 m-0'>
	<div class="row m-0 p-0" id="top_wrapper">
		<div class="col-2 logo-wrapper"><span class="h2 align-middle system-naming-span">СЕД НКНТУ</span></div>
		<div class="col-10 p-0">
		<?php if(Template::getBackButtonUrl()):?>
			<a href="<?=Template::getBackButtonUrl()?>" class="top-back-button"><i class="fas fa-chevron-left"></i></a>
		<?php endif;?>
		</div>
	</div>
	<div id="content_wrapper" class="row">
		<div class="col-2 p-0" id="left_side">
			<div id="fixed-wrapper">
			<div class="row m-0 p-0">
			<div class="col-3 p-1 pr-0"><img class="img-fluid" src='/public/img/noavatar.png'></div>
			<div class="col-8 p-1 pl-0">
				<span class="align-middle">
					<?= $profile->get('last_name').' '.$profile->get('first_name').' '.$profile->get('middle_name') ?>
				</span>
				<div class="text-sm font-weight-bold">
					<?if(!empty($profile->getDepartment())):?>
						<?=$profile->getDepartment()->get('name')?>
					<?endif;?>
				</div>
				<div class="text-sm" style="line-height: 1.2">
					<?if(!empty($profile->getGroupsList())):?>
						<?=$profile->getGroupsList()?>
					<?endif;?>
				</div>
			</div>
			</div>
			<?if(!empty($profile->getDepartment())):?>
				<ul>
					<li>
						<a href="<?=$router->url('', 'panel/documents')?>">
							Документи станції 
							<span class="badge badge-info">
								<?=Database::query("SELECT COUNT(*) FROM `departments_documents` WHERE `department_id` = ?", [intval($profile->get('department_id'))])?>
							</span>
						</a>
					</li>
					<li>Вхідні
						<ul>
							<li>Накази</li>
							<li>Розпорядження</li>
							<li>Листи</li>
						</ul>
					</li>
					<li>Вихідні
						<ul>
							<?if($profile->getDepartment()->getPermission('allow_decree')):?><li>Накази</li> <?endif;?>
							<?if(!empty($profile->getDepartment()->getChildrens())):?><li>Розпорядження</li> <?endif;?>
							<li>Листи</li>
						</ul>
					</li>
				<?php if($profile->hasPermission('handle_archive')): ?>
					<li>Архів
						<ul>
							<li><a href="<?=$router->url('requests', 'panel/archive')?>">Вхідні заявки</a></li>
						</ul>
					</li>
				<?php endif; ?>
				</ul>
				<?if($profile->getDepartment()->getPermission('allow_decree')):?>
					<div class="p-1"><a class="btn btn-primary btn-block" href="/document/new/">Створити наказ</a></div>
				<?endif;?>
				<?if(!empty($profile->getDepartment()->getChildrens())):?>
					<div class="p-1"><a class="btn btn-primary btn-block" href="/document/new/">Створити розпорядження</a></div>
				<?endif;?>
				<div class="p-1"><a class="btn btn-primary btn-block" href="/document/new/">Створити лист</a></div>
				<div class="p-1"><a class="btn btn-primary btn-block" href="<?=$router->url('create/', 'panel/documents')?>">Завантажити документ</a></div>
			<?endif;?>
			</div>
		</div>
		<div class="col-10 p-3" id="content"><?php include_once(PathManager::template($router->getModule()->getName(), $router->getModule()->getTypeName())); ?></div>
	</div>
</div>