<div class="center-block p-3" id="auth_block">
<form class="auth-form" method="post" action="<?=$router->url("", "reg")?>">
<?=$sessionAlerts->display()?>
<p><label><?=_("Last name")?>:</label><input class="form-control" type="text" name="last_name"></p>
<p><label><?=_("First name")?>:</label><input class="form-control" type="text" name="first_name"></p>
<p><label><?=_("Middle name")?>:</label><input class="form-control" type="text" name="middle_name"></p>
<p><label><?=_("E-mail")?>:</label><input class="form-control" type="text" name="email"></p>
<p><label><?=_("Password")?>:</label><input class="form-control" type="password" name="password"></p>
<p><label><?=_("Password confirm")?>: </label><input class="form-control" type="password" name="password_confirm"></p>
<?=$captcha->display()?>
<p class="text-center">
	<input class="btn btn-block btn-primary" type="submit" value="Register" name="submit_form">
	<a href="/"><?=_('Back to main page')?></a>
</p>
</form>
</div>